# Agile Project Template
# Full agile workflow with sprints and comprehensive issue types
# Includes Epic, Story, Bug, Spike, and Chore support

name: "Agile"
description: "Full agile workflow with comprehensive issue types including Epics and Spikes"
config:
  project_name: "{{project_name}}"
  issue_states:
    values:
      - Todo        # Backlog items
      - InProgress  # Active sprint work
      - Verify      # Code review/testing phase
      - Done        # Completed work
  issue_types:
    values:
      - Epic
      - Feature
      - Bug
      - Spike
      - Chore
