# Agile Project Template
# Full agile workflow with sprints and comprehensive issue types
# Includes Epic, Story, Bug, Spike, and Chore support

name: "Agile"
description: "Full agile workflow with comprehensive issue types including Epics and Spikes"
config:
  project_name: "{{project_name}}"
  issue_states:
    - Todo        # Backlog items
    - InProgress  # Active sprint work
    - Verify      # Code review/testing phase
    - Done        # Completed work
  issue_types:
    - Epic
    - Feature
    - Bug
    - Spike
    - Chore
  tags:
    - "*"
  custom.fields:
    - "category"
    - "sprint"
