# Default Project Template
# Basic configuration with standard defaults

name: "Default"
description: "Basic project configuration using global defaults"
config:
  project_name: "{{project_name}}"
  tags:
    - "*"
  categories:
    - "*"
