# Kanban Project Template
# Continuous flow methodology with assignee tracking
# Emphasizes work-in-progress limits and assignee accountability

name: "Kanban"
description: "Continuous flow workflow with assignee requirements"
config:
  project_name: "{{project_name}}"
  issue_states:
    - Todo        # Backlog
    - InProgress  # Active work
    - Verify      # Review/Testing
    - Done        # Completed
  issue_types:
    - Feature
    - Bug
    - Epic
    - Chore
  tags:
    - "*"
  categories:
    - "*"
