# Kanban Project Template
# Continuous flow methodology with assignee tracking
# Emphasizes work-in-progress limits and assignee accountability

name: "Kanban"
description: "Continuous flow workflow with assignee requirements"
config:
  project:
    name: "{{project_name}}"
  issue:
    states:
      - Todo        # Backlog
      - InProgress  # Active work
      - Verify      # Review/Testing
      - Done        # Completed
    types:
      - Feature
      - Bug
      - Epic
      - Chore
    priorities:
      - Low
      - Medium
      - High
    tags:
      - "*"
  custom:
    fields:
      - "category"
