# Simple Project Template
# Minimal workflow: Todo -> InProgress -> Done
# Suitable for personal projects or small teams

name: "Simple"
description: "Minimal workflow with three states and basic issue types"
config:
  project_name: "{{project_name}}"
  issue_states:
    - Todo
    - InProgress
    - Done
  issue_types:
    - Feature
    - Bug
    - Chore
  categories:
    - frontend
    - backend
    - docs
  tags:
