# Simple Project Template
# Minimal workflow: Todo -> InProgress -> Done
# Suitable for personal projects or small teams

name: "Simple"
description: "Minimal workflow with three states and basic issue types"
config:
  project_name: "{{project_name}}"
  issue_states:
    values:
      - Todo
      - InProgress
      - Done
  issue_types:
    values:
      - Feature
      - Bug
      - Chore
  categories:
    values:
      - frontend
      - backend
      - docs
  tags:
    values:
      - "*"
